#cloud-config

write_files:
  - content: |
      {
        "server": true,
        "datacenter": "awesome-datacenter",
        "bind_addr": "0.0.0.0",
        "client_addr": "0.0.0.0",
        "bootstrap_expect": 3,
        "retry_join": ["provider=aws tag_key=Consul tag_value=consul-server region=eu-west-1"],
        "data_dir": "/opt/consul/data",
        "leave_on_terminate": true,
        "connect": {
          "enabled": true
        },
        "ui_config": {
          "enabled": true
        }
      }
    path: /etc/consul.d/consul.hcl
  - content: |
      sed -i "s/\"bind_addr\": \"0.0.0.0\"/\"bind_addr\": \"$(hostname -I| awk '{print $1}')\"/" /etc/consul.d/consul.hcl
    path: /root/configure_consul.sh
    permissions: 744

yum_repos:
  hashicorp:
    baseurl: "https://rpm.releases.hashicorp.com/AmazonLinux/$releasever/$basearch/stable"
    name: hashicorp
    enabled: true
    gpgcheck: true
    gpgkey: https://rpm.releases.hashicorp.com/gpg

packages:
  - consul


runcmd:
  - ['bash', '/root/configure_consul.sh']
  - ['systemctl', 'start', 'consul']
